---
OrdererOrgs:
  - Name: vku.udn.vn
    Domain: vku.udn.vn
    Specs:
      - Hostname: orderer1
        SANS:
          - 172.30.127.73
      - Hostname: orderer2
        SANS:
          - 172.30.127.73
      - Hostname: orderer3
        SANS:
          - 172.30.127.73

PeerOrgs:
  - Name: ba.vku.udn.vn
    Domain: ba.vku.udn.vn
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.ba.vku.udn.vn
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.ba.vku.udn.vn
        SANS:
          - 172.30.127.73
      - Hostname: peer2
        CommonName: peer2.ba.vku.udn.vn
        SANS:
          - 172.30.127.73
  - Name: it.vku.udn.vn
    Domain: it.vku.udn.vn
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.it.vku.udn.vn
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.it.vku.udn.vn
        SANS:
          - 172.30.127.73
      - Hostname: peer2
        CommonName: peer2.it.vku.udn.vn
        SANS:
          - 172.30.127.73
